// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./components/Layout/Aside.vue')['default']
    Card: typeof import('./components/Card/index.vue')['default']
    Echart: typeof import('./components/Echart/index.vue')['default']
    Header: typeof import('./components/Layout/Header.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search/index.vue')['default']
    Table: typeof import('./components/Table/index.vue')['default']
  }
}

export {}
